[package]
name = "elfread"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"    
clap = {version="4.5.39", features=["derive"]}
owo-colors="4.2.1"
byteorder = "^1.5.0"
tabled = "0.20.0"